apiVersion: apps/v1
kind: Deployment
metadata:
  name: zombie
  namespace: zombie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zombie-app
  template:
    metadata:
      labels:
        app: zombie-app
    spec:
      containers:
      - name: z-cont
        image: ghcr.io/saisairepo/zombie:v1.3
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "2"
      imagePullSecrets:
      - name: zombie-secret
---
apiVersion: v1
kind: Service
metadata:
  name: z-service
  namespace: zombie
spec:
  selector:
    app: zombie-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: z-ingress
  namespace: zombie
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: z-service
            port:
              number: 80
